download:
  url: http://jensen.etit.tu-chemnitz.de:9010
  bucket: openalpr
  commit: eec6e1da4255
  path: OpenALPR/JPEGImages/

train:
  epochs: 1
  batch_size: 4

validate:
  conf_thres: 0.3
  iou_thres: 0.5
